#!/usr/bin/env python

import sys, socket, select, time, json, random

# states
CANDIDATE = 'candidate'
FOLLOWER = 'follower'
LEADER_STATE = 'leader'

LEADER = 'FFFF'
VALUES = {}
ELECTION_TIMEOUT = random.uniform(.15, .3)
STATE = FOLLOWER
TERM = 0
VOTES = 0
VOTED_FOR = None
BUFFER = []
LOG = [{}]
NEW_ENTRIES = []

# Your ID number
my_id = sys.argv[1]

# The ID numbers of all the other replicas
replica_ids = sys.argv[2:]

# For leaders: dict<replica_id, index>
next_index = {} # Keeps track of the next log index to send to replicas
match_index = {} # Keeps track of the highest log entry known to be replicated for each replica

# All servers: volatile state. initialized to 0, increases monotonically
commit_index = 0 # highest log entry known to be committed.
last_applied = 0 # highest log entry *applied*.

# Timestamps
last = 0
leader_seen = 0

# Connect to the network. All messages to/from other replicas and clients will
# occur over this socket
sock = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
sock.connect(my_id)

# Call after each election to re-initialize
def initialize_indices():
    global replica_ids, next_index, match_index
    for id in replica_ids:
        next_index[id] = commit_index + 1 # initialize to leader last log index + 1
        match_index[id] = 0 # initialized to 0, increases monotonically

def send_buffer():
    global BUFFER
    while (len(BUFFER) > 0):
        msg = BUFFER.pop()
        msg['leader'] = LEADER
        msg['dst'] = LEADER
        sock.send(json.dumps(msg))

# Handler functions
def msg_leader(msg):
    global VALUES, leader_seen, LEADER, STATE, FOLLOWER, TERM, NEW_ENTRIES
    res = None
    if msg['type'] == 'get':
        res = {'src': my_id, 'dst': msg['src'], 'leader': LEADER, 'type': 'ok', 'MID': msg['MID'], 'value': VALUES[msg['key']]}
    elif msg['type'] == 'put':
        VALUES[msg['key']] = msg['value']
        # update replicas, append_entries. TODO: this will be where we wait for commits
        for id in replica_ids:
            fwd = {'src': my_id, 'dst': id, 'leader': LEADER, 'term': TERM, 'type': 'append_entries', 'key': msg['key'], 'value': msg['value']}
            NEW_ENTRIES.append(fwd)
        res = {'src': my_id, 'dst': msg['src'], 'leader': LEADER, 'type': 'ok', 'MID': msg['MID']}
    elif msg['type'] == 'append_entries':
        #print(str(my_id) + ' leader receiving heartbeat')
        if (TERM < msg['term']):
            LEADER = msg['src']
            TERM = msg['term']
            leader_seen = time.time()
            STATE = FOLLOWER # they threw a coup :(
            # TODO implement commit stage here if msg['key']
    elif msg['type'] == 'request_vote':
        if (TERM < msg['term']):
            TERM = msg['term'] # they are democratically throwing a coup :(
            res = {'src': my_id, 'dst': msg['src'], 'leader': 'FFFF', 'type': 'vote', 'term': TERM}
            STATE = FOLLOWER # and we're going along with it :(
           # print('sending ' + msg['type'])
    if res: sock.send(json.dumps(res))

def msg_candidate(msg):
    global BUFFER, leader_seen, LEADER, STATE, FOLLOWER, TERM, VOTES, LEADER_STATE
    if msg['type'] in ['get', 'put']:
    # store the message until the election is over
        BUFFER.append(msg)
    elif msg['type'] == 'append_entries':
        #print(str(my_id) + ' candidate received heartbeat')
        leader_seen = time.time()
        LEADER = msg['src']
        STATE = FOLLOWER
        send_buffer()
        # TODO implement commit stage here if msg['key']
    elif msg['type'] == 'request_vote':
        if (TERM < msg['term']):
            leader_seen = time.time()
            TERM = msg['term']
            msg = {'src': my_id, 'dst': msg['src'], 'leader': 'FFFF', 'type': 'vote', 'term': TERM}
            VOTED_FOR = msg['src']
            STATE = FOLLOWER
            send_buffer()
            #print(str(my_id) + ' voting in term ' + str(TERM))
            sock.send(json.dumps(msg))
    elif msg['type'] == 'vote':
        if (TERM == msg['term']):
            leader_seen = time.time()
            VOTES = VOTES + 1
            if (VOTES > (len(replica_ids) + 1) / 2):
                #print(str(my_id) + ' is now leader')
                STATE = LEADER_STATE
                LEADER = my_id # declare victory
                send_buffer()
                VOTES = 0
                initialize_indices() # configure leader indices

def msg_follower(msg):
    global leader_seen, LEADER, TERM, BUFFER, VALUES
    if msg['type'] in ['get', 'put']:
        msg = {'src': my_id, 'dst': msg['src'], 'leader': LEADER, 'type': 'redirect', 'MID': msg['MID']}
        if (LEADER == 'FFFF'):
            BUFFER.append(msg)
        else:
            sock.send(json.dumps(msg))
    elif msg['type'] == 'request_vote':
        if (TERM < msg['term']):
            leader_seen = time.time()
            TERM = msg['term']
            msg = {'src': my_id, 'dst': msg['src'], 'leader': 'FFFF', 'type': 'vote', 'term': TERM}
            #print(str(my_id) + ' voting in term ' + str(TERM))
            VOTED_FOR = msg['src']
            sock.send(json.dumps(msg))
    elif msg['type'] == 'append_entries':
        leader_seen = time.time()
        if (TERM < msg['term'] or (TERM == msg['term'] and LEADER != msg['leader'])):
            LEADER = msg['src']
            TERM = msg['term']
            send_buffer()
        if (msg['key']):
            # TODO: change to log/commits
            VALUES[msg['key']] = msg['value']

while True:
    ready = select.select([sock], [], [], 0.02)[0]

    if sock in ready:
        msg_raw = sock.recv(32768)

        if len(msg_raw) != 0:
            msg = json.loads(msg_raw)
            if (msg['dst'] == my_id):
                if STATE == LEADER_STATE:
                    msg_leader(msg)
                elif STATE == CANDIDATE:
                    msg_candidate(msg)
                else:
                    msg_follower(msg)

    clock = time.time()
    if STATE == LEADER_STATE and clock-last > .12:
        # Heartbeats
        heartbeat = False if (len(NEW_ENTRIES) > 0) else True
        while len(NEW_ENTRIES) > 0:
            msg = NEW_ENTRIES.pop()
            sock.send(json.dumps(msg))
        if heartbeat:
            for id in replica_ids:
                msg = {'src': my_id, 'dst': id, 'leader': LEADER, 'term': TERM, 'type': 'append_entries', 'key': None, 'value': None}
                sock.send(json.dumps(msg))
        last = clock
    elif (STATE != LEADER_STATE) and (clock-leader_seen > ELECTION_TIMEOUT):
        STATE = CANDIDATE
        TERM = TERM + 1
        VOTES = 1
        #print(str(my_id) + ' request_vote: clock = ' + str(clock) + ' diff = ' + str(clock-leader_seen))
        leader_seen = time.time()
        for id in replica_ids:
            msg = {'src': my_id, 'dst': id, 'leader': LEADER, 'type': 'request_vote', 'term': TERM}
            sock.send(json.dumps(msg))
